In [ ]:
#예제1
symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

#예제2
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]
print(codes)


[36, 42, 38, 33, 64]
[36, 42, 38, 33, 64]


In [ ]:
#예제3
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

!~$$*&!@
[33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#예제4
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#예제5
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii,'\n')

print(f"Map function:\n>> {map(ord, symbols)}")
print(f"List after map:\n>> {list(map(ord, symbols))}")

[126] 

Map function:
>> <map object at 0x7fef8830b460>
List after map:
>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [ ]:
#예제6
colors = ["black", "white"]
sizes = ["S", "M", "L"]
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [ ]:
#예제7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [ ]:
#예제7
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols if ord(symbol)))

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [ ]:
#예제8
colors = ["black", "white"]
sizes = ["S", "M", "L"]

for tshirt in (f"{c} {s}" for c in colors for s in sizes):
  print(tshirt)

black S
black M
black L
white S
white M
white L


In [ ]:
#예제9

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f"{passport[0]}/{passport[1]}")
#예제10
for country, _ in traveler_ids:
  print(country)

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855
USA
BRA
ESP


In [ ]:
#예제11
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)


33.9425
-118.408056


In [ ]:
#예제12
a=10 ; b=20
a, b = b, a
print(a, b)

20 10


In [ ]:
#예제13
divmod(20, 8)


(2, 4)

In [ ]:
t = (20, 8)
divmod(*t)

(2, 4)

In [ ]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [ ]:
#예제14
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [ ]:
#예제15
a, b, *rest = range(5)
print(a, b, rest)

0 1 [2, 3, 4]


In [ ]:
a, b, *rest = range(3)
print(a, b, rest)

0 1 [2]


In [ ]:
a, b, *rest = range(2)
print(a, b, rest)

0 1 []


In [ ]:
#예제16
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [ ]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [8]:
#예제17
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]
print("{:15} | {:^9} | {:^9}".format("", "lat.", "long."))
fmt = "{:15} | {:9.4f} | {:9.4f}"

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [55]:
#예제18
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35, 139))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35, 139))

In [3]:
tokyo.population

36.933

In [4]:
tokyo.coordinates

(35, 139)

In [5]:
tokyo[1]

'JP'

In [9]:
#예제 19
City._fields

('name', 'country', 'population', 'coordinates')

In [10]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [11]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [12]:
#20
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [13]:
l[2:]

[30, 40, 50, 60]

In [14]:
l[:3]

[10, 20, 30]

In [15]:
l[3:]

[40, 50, 60]

In [17]:
#예제 21
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50   3    $52.50
1489  6mm Tactile                           $4.95    2    $9.90
"""
SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)

line_item = invoice.split('\n')[2:]
for item in line_item:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                 
    $4.95    6mm Tactile                       
 


In [18]:
#예제 22
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [21]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [25]:
l[3::2] = [11, 22]
l

[0, 1, 100, 11, 5, 22, 9]

In [26]:
#예제 23
l[2:5] = 100
l

TypeError: can only assign an iterable

In [27]:
#예제 24
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [28]:
#예제 25
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [29]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [30]:
#예제 26
board = [['_'] * 3 for i in range(3)]
board


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [31]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [32]:
#예제 27
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [33]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [34]:
#예제 28
row = ['_']*3
board = []
for i in range(3):
    board.append(row)
board[1][2] = 'X'
board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [35]:
#예제 29
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
print(board)
board[2][0] = 'X'
board


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [36]:
#예제 30
l = [1,2,3]
id(l)

133927762405696

In [38]:
l *= 2
l

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [39]:
id(l)

133927762405696

In [40]:
#예제 31
t = (1, 2, 3)
id(t)

133927764222208

In [41]:
t *= 2
id(t)

133927763521696

In [43]:
#예제 32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [44]:
#예제 33
print(t)

(1, 2, [30, 40, 50, 60])


In [54]:
#예제 34
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(sorted(fruits))

['apple', 'banana', 'grape', 'raspberry']


In [46]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [47]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [48]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [49]:
#예제 35
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [50]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [52]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [53]:
#예제 36
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.2914677580216123

In [57]:
#예제 37
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')
with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

floats2[-1]

0.2914677580216123

In [59]:
floats == floats2

True

In [63]:
#예제 38
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [64]:
memv [0]

-2

In [65]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [66]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [70]:
#예제 39
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
type(a)

numpy.ndarray

In [72]:
#예제 40
a.shape

(12,)

In [73]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
#예제 41
a[2]

array([ 8,  9, 10, 11])

In [75]:
a[2, 1]

9

In [76]:
a[:, 1]

array([1, 5, 9])

In [77]:
#예제 42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [78]:
#예제 43
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
dq.rotate(3)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [81]:
dq.rotate(-4)
dq

deque([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [82]:
#예제 44
dq.appendleft(-1)
dq

deque([-1, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [83]:
dq.extend([11, 22, 33])
dq

deque([0, 1, 2, 3, 4, 5, 6, 11, 22, 33])

In [84]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 0, 1, 2, 3, 4, 5])